#app.yaml
runtime: python38
entrypoint: gunicorn -b :$PORT main:app --timeout 120


#env_variables:
#  CLOUD_SQL_CONNECTION_NAME: chrome-octane-305110:europe-west2:flask-store
#  DB_USER: <USER>
#  DB_PASS: <PASS>
#  DB_NAME: <DB>


